apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-page-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-page
  template:
    metadata:
      labels:
        app: sample-web-page
    spec:
      containers:
        - name: tomcat-sample-web-page
          image: sandysanjeev2/samplewebapp:latest$BUILD_NUMBER
          ports:
            - containerPort: 8080
      imagePullSecrets:
          - name: sandysanjeev2
