apiVersion: v1
kind: Service
metadata:
  name: sample-web-page-service
spec:
  selector:
    app: sample-web-page
  type: NodePort
  ports:
    - nodePort: 30088
      port: 80
      targetPort: 8080
